export default {
	showLoading:({commit})=>{
		commit('showLoading');
	},
	hideLoading:({commit})=>{
		commit('hideLoading');
	},
	showRemind:({commit})=>{
		commit('showRemind');
	},
	hideRemind:({commit})=>{
		commit('hideRemind');
	},
	showLogout:({commit})=>{
		commit('showLogout');
	},
	hideLogout:({commit})=>{
		commit('hideLogout');
	}
}